name: benchmark
permissions:
  contents: write
on:
  workflow_dispatch:
    inputs:
      n_primes:
        description: 'Max number of primes to generate'
        default: '10000'
        required: true
      segments:
        description: 'Segments to be bucketed'
        default: '10'
        required: true

jobs:
  lang_benchmark:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
      
      - name: Install matplolib
        run: |
          python3 -m pip install matplotlib
      
      - name: Run all
        run: |
          chmod +x run.sh && ./run.sh all ${{ inputs.n_primes }} ${{ inputs.segments }}
      
      - name: Merge generated image
        uses: EndBug/add-and-commit@v9
        with:
          message: 'benchmark image and updated Reamdme'

      
      