name: benchmark
on:
  workflow_dispatch:
    inputs:
      n_primes:
        description: 'Max number of primes to generate'
        default: '10000'
        required: true
      segments:
        description: 'Segments to be bucketed'
        default: '10'
        required: true
      language:
        description: 'Choose from below'
        default: 'all'
        required: true
        type: choice
        options:
          - all
          - python
          - rust

jobs:
  python_benchmark:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      
      - name: Run all
        run: |
          chmod +x run.sh && ./run.sh all ${{ inputs.n_primes }} ${{ inputs.segments }}
      
      - name: Echo results
        run: |
          cat benchmark_python && cat benchmark_rust
      
      
      